import { SiteHeader } from "@/components/site-header";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import "@/styles/home.css";
import { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import AppProvider from "./provider";

export const fontSans = FontSans({
	subsets: ["latin"],
	variable: "--font-sans",
});
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn(
					"pt-16",
					"min-h-screen bg-background font-sans antialiased flex flex-col",
					fontSans.variable
				)}
			>
				<AppProvider>
					<SiteHeader />
					{children}
				</AppProvider>
			</body>
		</html>
	);
}
